# x='[abc]' either a b or c
# x='[^abc]'except abc
# x='[a-z]' a to z
# x='[A-Z]' A to Z
# x='[a-zA-Z]' BOTH LOWER AND UPPER CASE ARE CHECKED
# x='[0-9]' check digits
# x='[a-zA-Z0-9]' SPECIAL symbols
# x='\s' check space
# x='\d' check the digits
# x='\D' except digits
# x='\w' all words except special character
# x='\W' FOR special characters